### ISSUE TITLE
ssh-keygenで使用するメールアドレスが直打ちで使われている

### ISSUE THREAD

**Issue by Ancient-Scapes** [ryuta69/dotfiles#4]
https://github.com/ryuta69/dotfiles/blob/master/install.sh の168行目あたり

できれば環境変数を使用するのが望ましい(メールアドレスを悪用される可能性がある)

**Comment by Ancient-Scapes** [comment]
CIで使う環境変数はSettingsのSecretsから定義可能

**Comment by ryuta69** [comment]
これ確かに不安だなと思ったんですが、悪用できないとも思ってるんですよね・・・

- このsshkeyは、私のプライベートのgithubでしか使用してない
- 私のgithubは２段階認証を使用している
- 鍵の複製やなりすましは不可能だし、仮に想定外の迷惑行為をされても最悪プライベートの範囲で収まる

またGithubで使用しているメールアドレス自体は、既に多くの人が.gitconfigでVerified Signを出すために公開してます。
https://github.com/b4b4r07/dotfiles/blob/master/.gitconfig#L48
https://github.com/suin/dotfiles/blob/master/.gitconfig#L3

といった理由で問題ないかと思ってますが、逆にどういうケースで危険か知りたいです。

**Comment by Ancient-Scapes** [comment]
普通にメールアドレス直打ちされてるから、個人用メールアドレスが開示したくないかなと思っただけ！

**Comment by Ancient-Scapes** [comment]
なるほど

**Comment by Ancient-Scapes** [comment]
awsの公開鍵は悪用するやつがクローラー使ってめっちゃ仮想通貨サーバ立てまくったりするらしいから、メールアドレスも同じようなものあったらスパムメールきそうだなと

**Comment by Ancient-Scapes** [comment]
まあでも、大多数の人が公開してるなら問題ないか…

**Comment by Ancient-Scapes** [comment]
疑問は解決したのでclose
回答に感謝

**Comment by ryuta69** [comment]
>awsの公開鍵は悪用するやつがクローラー使ってめっちゃ仮想通貨サーバ立てまくったりするらしいから、メールアドレスも同じようなものあったらスパムメールきそうだなと

こちらは確かに怖くて、前はpre-commitにAWSキーのパターン（42字の英数字）がgit diffにいたら叩くスクリプト入れてたんですよね・・・（ものすごい前で今はほぼ入れないの間違いない自信から外してるけど、入れなおそうかな・・・と思ってたり）。[余談ですが今はpemだけチェックしています](https://github.com/ryuta69/dotfiles/blob/master/dotfiles/.git_template/pre-commit)。

危なそうなファイル、文字列はたしかに気をつけようと思いました。ありがとうございました。
