### ISSUE TITLE
現在使っているMac設定をdotFilesで使う時にわかるようなエクスポート方法は存在しますか？

### ISSUE THREAD

**Issue by Ancient-Scapes** [ryuta69/dotfiles#5]

**Comment by ryuta69** [comment]
（全部ふっとばしてとりあえずどれが何を示すかをすぐ知りたい場合、おそらく現状世界で一番自分のリポジトリが設定を網羅してると思うので[こちらを参照してください](https://github.com/ryuta69/dotfiles/blob/master/system/macos.sh)）

あります。
「**Macの環境設定を、再現できるように、dotfilesにコマンドとしてエクスポートする方法**」は、下記の通りです。

## フロー

1. 調べたいMac設定に一致するplist（Mac設定の保管場所）をググる（例：「設定名 plist」で大体出る）
2. ターミナルで `defaults read ○○.plist {{設定項目名}}` と打ち、設定値を確認（例：`defaults read .GlobalPreferences AppleInterfaceStyle` でテーマカラーの設定値が出る）
3. 新環境で再現したい時は、　`defaults write ○○.plist {{設定項目名}} {{設定値}}` とdotfilesのスクリプトに書く（例： `defaults read .GlobalPreferences AppleInterfaceStyle -string "Dark"` ）

これで**８割方**エクスポート可能です。
残り２割は、**電源やタイムマシンなどのルート設定に関するutil系**と、**sfl2という現状エクスポート方法が存在しない圧縮ファイル系**の、２つに存在する設定です（後ほど説明します）。

## ググっても出てこない場合の調べ方(defaults)

Mac設定のAPIは、公式のドキュメントが存在しないため「ググっても出てこない事」が多いです。
そのため、自分一人で探す方法を下記します（かなり力技なのでご了承ください）。

1. 調べたい項目を変更する
2. 更新されたplistを探す
```
Mac環境設定の保存先plistは主に下記の3つがあります。
${HOME}/Library/Preferences/*.plist
${HOME}/Library/Preferences/ByHost/*.plist
/private/var/root/Library/*.plist
```
3. defaults readで中身をログに書き出し、diffを取って更新された項目を確認する

これをすぐに実現するコマンドは下記の通りです。
```bash
# 1. 調べたい項目を変更する前に、全plistの中身を適当なログに保存
defaults domains | sed 's/ /\\n/g' | xargs -I % sh -c 'echo % && defaults read %' > ~/work/a.log && defaults domains --currentHost | sed 's/ /\\n/g' | xargs -I % sh -c 'echo % && defaults read --currentHost %' >> ~/work/a.log

# 2. 調べたい項目を変更したら、再度、全plistの中身を適当なログに保存
defaults domains | sed 's/ /\\n/g' | xargs -I % sh -c 'echo % && defaults read %' > ~/work/b.log && defaults domains --currentHost | sed 's/ /\\n/g' | xargs -I % sh -c 'echo % && defaults read --currentHost %' >> ~/work/b.log

# 3. diffを取って、更新された項目を確認する
diff ~/work/a.log ~/work/b.log
```

（かなり悪手だと思いますが、これより良い方法がありません。ドキュメントがない為。）

## ググっても出てこない場合の調べ方(util系コマンド)
**電源やタイムマシンなどのルート設定に関するutil系**は、plistではなく、pmsetやmdutilやscutilといったコマンドから操作が必要です。

Util系コマンドについてはこちらのリポジトリが詳しいです。
https://github.com/kevinSuttle/macOS-Defaults/blob/master/REFERENCE.md

例えば電源設定について、

```bash
# ========== Turn display off after ==========
# @int: minutes
sudo pmset -b displaysleep 3
```

といった風に操作します。設定一覧のリストを取得する事ができない為、ググるか他の人のdotfilesリポジトリを何百と漁って見つけるしかないでしょう・・・（が、結構ググりHIT率が高いのでそこまで苦労はしない）。

## ググっても出てこない場合の調べ方(sfl2)
**sfl2という現状エクスポート方法が存在しない圧縮ファイル系**に存在する設定は、現状取得不可能です（正確にいうとsidebarというプロジェクトでSwiftで取得できているようだが、かなり不安定らしいので無視）。

例えば、環境設定＞一般＞「最近みた項目を何個表示する？」の個数などがこれにあたり、`${HOME}/Application Support/com.apple.sharedfilelist/*.sfl2`に保存されています。

「エクスポートできないから諦める」わけではありません。目視で環境設定は見れるわけですので、「AppleScriptでGUI上で自動操作すればよい」のです。(ちなみにこれは、sqliteに保存される「デスクトップ画像」や、パソコン毎に異なる解像度を動的に取得している「環境設定>ディスプレイ>スペースを広く」も同様です。とりあえず「**これ無理だな、と思ったらAppleScript**」という認識で問題ないです)

```bash
    # 例：環境設定＞一般＞「最近みた項目を何個表示する？」->５個に設定する
	osascript -e "
		tell application \"System Preferences\"
			activate
			set current pane to pane \"com.apple.preference.general\"
		end tell
		tell application \"System Events\"
			tell application process \"System Preferences\"
				repeat while not (window 1 exists)
				end repeat
				tell window 1
					tell pop up button 4
						delay 1
						click
						tell menu 1
							click menu item \"5\"
						end tell
					end tell
				end tell
			end tell
		end tell
	"
```

### 参考
[参考までに、別記事でも解説してるので暇なときに御覧ください](https://ryuta69.netlify.app/automate-macos-preferences)（内容同じ）。

**Comment by Ancient-Scapes** [comment]
現状結構力技で大変なんですね〜
ありがとうございます〜
実装する時は参考にさせてもらいます！

**Comment by ulwlu** [comment]
Note

The article about this trends #1 in Zenn.

https://zenn.dev/ulwlu/articles/1c3a1da12887ed
